Lesson 17
Shadyspb/tutu pull request #3
Opened 2018-01-14 16:34 UTC by Shadyspb

Исправления недочетов из 16 задания, задание 17 и плюс маленькие корректировки.

2018-01-14 19:45 UTC, iBublik requested changes

2018-01-14 19:45 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +  def update_position
Между методами принято отступы оставлять

2018-01-14 19:45 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +def update_time
Тут что с уровнем отступов?

2018-01-14 19:45 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +    @route = Route.find(params[:route_id])
Зачем тут снова искать маршрут? Ты же в before_action это уже сделал

2018-01-14 19:45 UTC, iBublik commented on app/controllers/searches_controller.rb
> +  def search_params
Зачем этот метод? Не вижу чтоб он использовался как-то

2018-01-14 19:45 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    if params[:start_station] == params[:finish_station]
В идеале, конечно, выделить отдельный класс для поиска. В нем можно было бы такие проверки делать. Ну и чтоб он возвращал не только поезда, но и сами станции, по которым шел поиск - так меньше логики будет в контроллере

2018-01-14 19:45 UTC, iBublik commented on app/controllers/searches_controller.rb
> +      @error = "Станции не могут быть одинаковы."
Т.е. при переходе на страницу поиска пользователю сразу будет выдаваться ошибка? С точки зрения UI решение не очень хорошо :)

2018-01-14 19:45 UTC, iBublik commented on app/models/railway_station.rb
> +  scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.position').uniq }
Зачем оставлен скоуп выше? Ведь будет использовано последнее определение

2018-01-14 19:45 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route = station_route(route)
Зачем тут это присваивание? Вообще метод можно сократить до одной строки - `station_route(route)&.update(position: position)`. В других методах аналогично

2018-01-14 19:45 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route(route).try(:position)
Вместо `try` лучше использовать `&`, т.к. он более строгий (не позволяет вызывать на объектах несуществующие методы)

2018-01-14 19:45 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route ||= railway_stations_routes.where(route: route).first
Тут, по идее, должна быть инстанс-переменная, а не локальная. Иначе условное присваивание бессмысленно - на начало выполнения метода локальная переменная не была объявлена, так что код после "равно" будет всегда выполняться.
Так же сам поиск можно упростить - `railway_stations_routes.find_by(route: route)`

2018-01-14 19:45 UTC, iBublik commented on app/models/ticket.rb
> +  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
Имя внешних ключей указывать нет смысла, т.к. нейминг совпадает с конвенцией, значит рельсы сами найдут нужное поле для связи

2018-01-14 19:45 UTC, iBublik commented on app/views/routes/show.html.erb
> +        <td>
Соблюдай отступы - сейчас из-за неправильного уровня очень тяжело понять где тело формы завершается

2018-01-14 19:45 UTC, iBublik commented on app/views/searches/show.html.erb
> +      <%= select_tag :start_station, options_from_collection_for_select(RailwayStation.all, :id, :title), { class: 'form-control' } %>
Ты же специально в контроллере уже загрузил все станции в `@stations`, почему тут не использовать?

2018-01-14 19:45 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    if params[:start_station] == params[:finish_station]
Подумай над тем как это сделать (нужен обычный Ruby класс), если не получается - оставляй как есть

2018-01-14 19:45 UTC, iBublik commented on app/views/searches/show.html.erb
> +      <% else %>
С отступами прям кошмар какой-то. Давно пора это в редакторе настроить

2018-01-14 19:45 UTC, iBublik commented on db/migrate/20171212205415_add_user_id_to_tickets.rb
> +    add_belongs_to :tickets, :start_station, index: true
Индекс в 5 рельсе ставится по умолчанию

2018-01-14 19:45 UTC, iBublik commented on app/views/tickets/new.html.erb
> +  <%= form.hidden_field :train_id, value: params[:train_id] %>
Если при сохранении возникли ошибки, этих значений в params уже не будет, так что билет будет создаваться без указания поезда и станций

2018-01-15 08:02 UTC, vkurennov approved these changes

2018-01-15 08:02 UTC, vkurennov approved these changes

2018-01-15 19:21 UTC, closed without merging